### ISSUE TITLE
The following resource failed to create: [LambdaCustomResource].

### ISSUE THREAD

**Issue by Kasper-M** [aws-quickstart/quickstart-cloudstax-nosql#10]
I try to set-up a cloudformation stack based on this quickstart cassandra template.
https://github.com/aws-quickstart/quickstart-cloudstax-nosql
The following resource(s) failed to create: [LambdaCustomResource] 
Failed to create resource. Bad Request

Parameters:
zones: eu-west-1a,eu-west-1b,eu-west-1c
CassandraRelease: 3.11
FireCampRelease: 0.9.6

Based on the error message from AWS I have no clue how to fix this error.
Does someone has any ideas?

**Comment by avattathil** [comment]
Please try launching it from here  [https://aws.amazon.com/quickstart/architecture/cloudstax-nosql-db-for-cassandra]( https://fwd.aws/nekJa)

**Comment by Kasper-M** [comment]
Solved issue by using FireCampRelease: 1.0
